import {StyleSheet} from 'react-native';

const Loginstyle = StyleSheet.create({
  head_container: {
    display: 'flex',
    width: 'auto',
    paddingVertical: '15%',
    paddingHorizontal: 30,
    flexDirection: 'column',
  },
  head1_text: {
    color: 'orange',
    fontFamily: 'Kanit-Bold',
    fontSize: 30,
  },
  head2_text: {
    color: 'orange',
    fontFamily: 'Kanit-Bold',
    fontSize: 40,
  },
  form_container: {
    display: 'flex',
    width: '100%',
    padding: 20,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
  },
  input_container: {
    width: '100%',
    display: 'flex',
    gap: 5,
  },
  input_label: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignSelf: 'stretch',
    fontSize: 18,
    fontFamily: 'Kanit-Regular',
    color: 'black',
  },
  input_box: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    height: 'auto',
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRadius: 15,
    borderColor: '#DCDCDC',
    borderWidth: 1,
    gap: 10,
  },
  input_text: {
    color: 'black',
    fontSize: 20,
    fontFamily: 'Kanit-Regular',
    fontWeight: 'bold',
    alignContent: 'center',
  },
  vertical_line: {
    height: '70%',
    width: 2,
    backgroundColor: 'gray',
  },
  request_container: {
    display: 'flex',
    width: 300,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    backgroundColor: 'orange',
  },
  request_text: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'Kanit-Regular',
    fontWeight: 'bold',
    fontWeight: 400,
  },
  request_again: {
    display: 'flex',
    width: 300,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'orange',
    borderRadius: 30,
  },
  requestagain_text: {
    color: 'orange',
    fontSize: 18,
    fontFamily: 'Kanit-Regular',
    fontWeight: 'bold',
    fontWeight: 400,
  },
  help_container: {
    display: 'flex',
    gap: 5,
  },
  help_text: {
    color: 'black',
    fontSize: 16,
    fontFamily: 'Kanit-Regular',
    fontWeight: 400,
  },
  contract_text: {
    color: 'orange',
    fontSize: 16,
    fontFamily: 'Kanit-Regular',
    fontWeight: 400,
    textDecorationLine: 'underline',
  },
});

export default Loginstyle;
